# # 镜像版本
# FROM nginx

# # 镜像作者
# LABEL maintainer="19A"

# # 环境变量
# ENV NODE_ENV=production

# # 工作目录
# WORKDIR /todo/client

# # 制文件到容器里指定路径
# COPY . /todo/client

# # 设置依赖下载地址
# RUN yarn config set registry "https://registry.npm.taobao.org/"

# # 拉取依赖
# RUN yarn

# # 暴露端口
# EXPOSE 80

# # 启动
# CMD yarn start


