# 镜像版本
FROM node

# 工作目录
WORKDIR /node

# 制文件到容器里指定路径
COPY . /node

# 设置依赖下载地址
RUN yarn config set registry "https://registry.npm.taobao.org/"

# 拉取依赖
RUN yarn

# 暴露端口
EXPOSE 3000 8888

# 启动
CMD yarn start
